### ISSUE TITLE
Does arrivalOffset and departureOffset matter - low rail ridership

### ISSUE THREAD

**Issue by gac55** [matsim-org/matsim-libs#1188]
We are seeing low ridership on some specific rail routes. We have been trying to understand why

We noted that our arrivalOffset and departureOffset are the same. 

e.g 

```
<transportMode>rail</transportMode><routeProfile><stop refId="sfhifsdfdsh" arrivalOffset="00:12:40" departureOffset="00:12:40" awaitDeparture="false"/>
<stop refId="sfhifsdfdsh" arrivalOffset="00:18:40" departureOffset="00:18:40" awaitDeparture="false"/>
```

When looking at the excellent Berlin example, we see a 30 second "stop" between `arrivalOffset` and `departureOffset`.

```
<transportMode>rail</transportMode><routeProfile><stop refId="060200005030" arrivalOffset="00:00:00" departureOffset="00:00:00" awaitDeparture="false"/>
<stop refId="060200006102" arrivalOffset="00:02:06" departureOffset="00:02:36" awaitDeparture="false"/><stop refId="060200007102" arrivalOffset="00:05:30" departureOffset="00:06:00" awaitDeparture="false"/><stop refId="060200008006" arrivalOffset="00:08:54" departureOffset="00:09:24" awaitDeparture="false"/
```

Is it possible that this results in an agents not being able to board the service? We have set boarding time as being `0` and had previously assumed that boarding would be possible

**Comment by vsp-gleich** [comment]
Differences between arrivalOffset and departureOffset at the same TransitRouteStop should have only limited influence on ridership levels. The only purpose is to allow for some time at the stop such that a certain number of boarding and alighting passengers can board and alight without causing delay to the train. If arrivalOffset nad departureOffset are equal and the train arrives on time, any passenger boarding or alighting will cause the train to be delayed (unless boarding time is 0).
So the problem you are facing has probably a different cause. I see that awaitDeparture is set to false, something I fixed in the recent matsim-berlin version. While that itself only causes trains to depart before schedule if they arrive early (agents might miss the train but might profit from lower than scheduled travel times), it could be a sign that you should also check link freespeeds of your pt links. There was an old rather slow default value, which if not overwritten, caused especially faster rail services to be delayed. So I would suggest you set awaitDeparture "true" and check for delays, e.g. with Via or looking at events.

**Comment by gac55** [comment]
Thank you @vsp-gleich . Very helpful.

One thing I omitted to mention is that we are using the SBB deterministic implementation to ensure they follow their timetable. I wonder how these would interact?

**Comment by vsp-gleich** [comment]
I can't say much about the SBB deterministic implementation. As far as I know it should ignore link freespeeds and likely also the awaitDeparture setting and just teleport the vehicle with arrival and departure always on time. So my suggestions above would not apply. Nevertheless, I would reccommend to check whether trains run on time (maybe the SBB plugin is not enabled correctly). Other reasons for low pt ridership might concern scoring parameters (rail being too unattractive) or a population file with travel demand not matching well real world conditions.

**Comment by mrieser** [comment]
late reply regarding deterministic pt simulation: 
It depends on how fast agents can board and alight the transit vehicles, which is an attribute of the transit vehicles. Essentially, with deterministic simulation, the transit vehicles arrive at the specified arrivalOffset. Then, agents alight and board as fast as they can, after that, the vehicle departs. If `arrivalOffset` and `departureOffset` are equal, the vehicle will likely depart with some delay. Nonetheless, it will arrive on time at the next stop (except the delay is so huge that it would have to travel backwards in time, then, the vehicle will just arrive in the following second at the next stop).

as the arrival time is often more crucial for catching connecting services, the usage of the deterministic pt simulation should not have a big impact on ridership, as the vehicles will arrive on time in most cases.

**Comment by gac55** [comment]
Thanks all - very useful (and re-assuring!).
