### ISSUE TITLE
Introduce re-assignments in DVRP

### ISSUE THREAD

**Issue by sebhoerl** [matsim-org/matsim-libs#1298]
We're currently in the process of bringing the algorithms of AMoDeus closer to MATSim / DRT by removing most of the duplicated functionality from AMoDeus and re-using as many components as possible. The major difference between the existing algorithms in MATSim and AMoDeus is that AMoDeus often re-assigns requests. Once a vehicle is assigned to a request, this is assignment is not binding, and another vehicle may take over before the passenger is picked up.

Currently, `PassengerRequestScheduledEvent` exists in DVRP. In the current development version, we are publishing this event every time a new assignment happens, including the updated expted pickup and dropoff time. This works without problems with the existing analysis infrastructure of DRT (in the analyzer the old assignment is just replaced by the new one).

We have now started to optionally let people use DRT rebalancers with AMoDeus algorithms. There, we face problems now, because at least one rebalancer (tested with `PlusOne`) assumes implicitly that there is one `PassengerRequestScheduledEvent` per request. It is easy to fix (basically adding one line of code), but I would propose to go a more structured way. To be prepared for future algorithm implementation, I would propose to have two events:

- `PassengerRequestScheduledEvent` - when an assignment between request and vehicle takes place
- `PassengerRequestUnscheduledEvent` - when an existing assignment is revoked

The rule is that a request can only be un-scheduled if it is already scheduled, and it can only be schedule if it is not scheduled yet. We can test this implicitly by extending the analysis scripts where we calculate the open requests, unscheduled and scheduled requests and where the analyzer is counting the current state.

What do you think? @michalmac

**Comment by sebhoerl** [comment]
Related to that, we noticed that rebalancing in DRT is always binding. When a vehicle is sent to a link, it first must arrive there, it cannot be diverted. However, realistically an operator would divert the vehicle when it makes sense. I would therefore propose to replace the `RELOCATE` vehicle task type by a process where events are sent, one when a rebalancing trip starts, and one when it ends, e.g. `drt relocation started` and `drt relocation ended`.

**Comment by michalmac** [comment]
> To be prepared for future algorithm implementation, I would propose to have two events:
>
> - PassengerRequestScheduledEvent - when an assignment between request and vehicle takes place
> - PassengerRequestUnscheduledEvent - when an existing assignment is revoked

I like this idea. We are gradually adding new events on demand. So since there is a need for this kind of events, let's add it.

However, I suggest to send one event instead, that is `PassengerRequestRescheduledEvent`. A couple of reasons:
- maintain backward compatibility (old code, also outside matsim, may assume one `PassengerRequestScheduledEvent`)
- especially for the outside observer (listening to events), reassigning a request to another vehicle is an atomic update operation
- in case we want to notify about delays (as the event is not only about the assigned vehicle but also about the timing), we can also use `PassengerRequestRescheduledEvent` (just feels more natural for this type of changes to use "rescheduled" rather than "unscheduled + scheduled").

(I imagine that in some cases handling "unscheduled + scheduled" events could be easier to implement.)

**Comment by michalmac** [comment]
> Related to that, we noticed that rebalancing in DRT is always binding. When a vehicle is sent to a link, it first must arrive there, it cannot be diverted.

Right. This should be changed. Probably initially we run rebalancing every 30 min, so that was not a problem. But given the latest developments, vehicles being rebalanced should be considered rebalancable.

@luchengqi7 @tschlenther I would need to slightly adjust the existing rebalancing algorithms. Any objections or potential problems on the horizon?

>  I would therefore propose to replace the RELOCATE vehicle task type by a process where events are sent, one when a rebalancing trip starts, and one when it ends, e.g. drt relocation started and drt relocation ended.

What is the difference between updating a vehicle path in the data-like rebalancing task to sending an event to the process-like rebalancing task?

I think you could try to experiment with this approach. It should be possible at the level of DynAgents/DVRP, but may require some changes in DRT. But I somehow feel it is clearer to have a rebalancing task as a regular schedule element, especially given that there is a central DRT optimiser orchestrating all schedules.

BTW. Currently rebalancing is always the last task, but with advance requests being inserted into schedules (prebooking), this may not longer be the case. So we would like to be able to query and update the start/end links/times to make sure the schedule is valid and to act if the schedule becomes infeasible.

**Comment by tschlenther** [comment]
> @luchengqi7 @tschlenther I would need to slightly adjust the existing rebalancing algorithms. Any objections or potential problems on the horizon?

I do not see problems for the rather simple rebalancing approaches i was working on. In contrast, this would also prevent artefacts like the one we faced when we sent vehicles outside of the service area (because target link was there) which then got 'lost' and never re-assigned. And it should improve service quality notably.

**Comment by luchengqi7** [comment]
I also think there won't be any big problems. We can go through the algorithms together, as some of the rebalancing algorithms may need some slight adjustment. So please go ahead.

@sebhoerl For the Rebalancing algorithms in MATSim, the only (and not very important) reason why I use the PassengerRequestScheduledEvent is that some requests may be rejected (e.g. due to wait time constraint). And PassengerRequestScheduledEvent is just a little more convenient to use at the beginning (as we don't send vehicles to ther area where request are rejected). As we are making the DRT to include more features, I am very happy to change to using other event handler for rebalancing.  

@tschlenther A thought from my side regarding the "lost" vehicles: I think after changing our get zone Id for link from using link.getCoord() to link.getToNode().getCoord(), there is now no requests outside the zonal system (as long as the zonal system covers the whole service area). So I guess vehicle will no longer be sent to ouside of the service area?

**Comment by michalmac** [comment]
> maintain backward compatibility (old code, also outside matsim, may assume one PassengerRequestScheduledEvent)

I meant here that `PassengerRequestScheduledEvent` has been used so far as a counterpart to the rejection event. And for determining the vehicle and pickup/dropoff times, we typically use the pickup and dropoff events as they contain the final information.

===

Alternatively, what if we remove `vehicleId` from `PassengerRequestScheduledEvent` and do not add `PassengerRequestRescheduledEvent`? In the current prebooking (**beta**), we use `TripInfo` updates to communicate with the passenger (so there we would have some duplication with (re)schedule events). On the other hand, without prebooking, maybe we do not need updating the passegners as they do not have any option besides waiting?

@sebhoerl How/where are you using the vehicle Id from (re)schedule events?

**Comment by sebhoerl** [comment]
Thanks for all your feedback!

- I think `PassengerRequestRescheduledEvent` is fine, I think the backwards compatibility point is valid and this is some "added functionality". To answer the last question: I guess the main point is to have more insights into how the selected algorithm is working. Think of making a visualization like we showed for AMoDeus: Everythime the vehicle changes that is on the way to a specific request you would want to update a line connecting the vehicle and the travelers.

- Regarding the `rebalancing` task type. Currently, it is just a specific `drive` task and the only reason why it is `rebalancing` is (at least how far I understand) to make analysis easier (for the vehicle state plot). However, as soon as re-assignments are possible it is not completely clear anymore when something is a `rebalancing` drive. I'm actually not thinking of diverting a rebalancing vehicle to a new destination. But I'm thinking of diverting a rebalancing vehicle to pick somebody up. One option would be to end the `rebalancing` task and start a `drive` task, which would make the vehicle stop at the link and then continue the journey. However, ideally, the vehicle would just be diverted to drive to the customer. In that case what was a "rebalancing" `drive` becomes an "ordinary" `drive`. That's why I decided to add `RelocationStartEvent` and `RelocationEndEvent` in our current project, to indicate, whenever a vehicle is driving.

I could send PRs for the two propositions, then we can discuss more practically.

**Comment by michalmac** [comment]
**PassengerRequestRescheduledEvent** 

Would be great if you could submit a PR. Thanks!

===

**Rebalancing task type**

I see your point. Yes, changing drive type while driving is not possible yet. Probably it should be modelled as on-the-fly switching from one drive task to another. For the time being, I think it is best/easiest/safest to simply stop at a link and start a new drive task.

PROS:
Task types are used in (post) analysis but also in decision making. I think it is simpler to have just one source of truth (task - inside the optimiser, and corresponding task start/end events - for external observers) rather than having partial information distributed over many data structures that needs additional merging.

CONS:
With `insertingWaitingVehiclesBeforeDrivingVehicles` enabled (required by DVRP) there may be some little artefacts related to leaving and re-entering the traffic, but I would not worry about this (there are bigger sources of inaccuracies, e.g. beeline distances or poor zoning). With on-the-fly task switching, this will not be a problem anymore.

**Comment by sebhoerl** [comment]
Yes, I agree that the tasks should stay consistent. They provide a nice log of what the vehicle was doing and there are some things that can change (destination if there is a diversion, or end time), while some are guaranteed to stay constant (task type sequence). Though this is where I would then only have a "drive" task, because it describes sufficiently what the vehicle did (it drove somewhere). If it was to a rebalancing destination or to a customer does not matter so much from the perspective of the vehicle or of the observer ("it was driving to link A"). So maybe the task analysis should not make this difference.

I would then say that the rebalancer is a somewhat different component, because you can run dispatching just without having any rebalancer. And that it is the duty of the rebalancer to provide additional information on the strategy, if required. We can discuss this again later on, but maybe it could also make sense to have only "drive" in the state analysis and have a separate one (active if any rebalancer is chosen) that performs additional analysis based on some events that are supposed to be sent by the rebalancer. Just some additional perspective :)

**Comment by michalmac** [comment]
I agree that for analysis we could use either of the approaches. However when it comes to decision making, I see the two following issues when using events:

1. **race conditions** (when events are pushed through the standard matsim event pipeline): Depending on which component is executed first in a sim step either the optimiser may not be aware that a vehicle has just started rebalancing, or the rebalancer may not be aware that a vehicle has just been just sent somewhere. This may potentially lead to some hard-to-find bugs.

2. **cannot represent decisions about future tasks**: If we run rebalancing every 5 minutes, we may want to plan rebalancing also for vehicles which will become idle in 30 sec. However, the optimiser will not know about it until 30 sec passes as only then a `RelocationStartEvent` is sent.

If we have another component, e.g. responsible for sending low-charged vehicles to chargers, and we add (potentially) add more event types to the pipeline, it may become harder to work around potential race conditions (or make sure they will have no impact) or to reason about the near future plans.

> maybe it could also make sense to have only "drive" in the state analysis and have a separate one (active if any rebalancer is chosen) that performs additional analysis based on some events that are supposed to be sent by the rebalancer.

In the current implementation, we have a fixed set of base task types (stay, stop and drive) and in parallel to that we have an "extendible" task set that can be flexibly shaped. So we can use both kinds of vehicle task types for analysis. I even think we are only one step away from having that flexibility in classes like `DrtVehicleOccupancyProfileCalculator` (there is a hardcoded mapping of task types to categories).

**Comment by michalmac** [comment]
But I have to admit that task types have some limits. As an example let's take the charging task type. Easy to model visits at chargers, but not so super obvious how to best represent opportunistic charging (e.g. while staying at a stop and dropping off/picking up passengers).
