### ISSUE TITLE
RunAverageEmissionToolOfflineExample produces empty output

### ISSUE THREAD

**Issue by nkuehnel** [matsim-org/matsim-libs#1342]
Hi all and happy new year,

I'm currently getting empty output files when running the "RunAverageEmissionToolOfflineExample" - does anybody know why that could be?

5.emission.events.offline.xml:

`<?xml version="1.0" encoding="utf-8"?>
<events version="1.0">
</events>`

Thanks
Nico

**Comment by ikaddoura** [comment]
Hi Nico, I was also running into some problems with the emissions events analysis in the last few days. In my case, the problem was, that the that the new default events manager is the ParallelEventsManager which seems to have some problems with multiple handlers and simultaneous writing of events..., see here: https://github.com/matsim-org/matsim-libs/issues/1091

**Comment by mrieser** [comment]
I had a quick look at `RunAverageEmissionToolOfflineExample`. Could you try if it works if you modify the code to call `events.initProcessing();` before reading the events, and `events.finishProcessing();` after reading the events, something like this:


```java
....
final String outputDirectory = scenario.getConfig().controler().getOutputDirectory();
EventWriterXML emissionEventWriter = new EventWriterXML( outputDirectory + emissionEventOutputFileName );
emissionModule.getEmissionEventsManager().addHandler(emissionEventWriter);

eventsManager.initProcessing(); //   <----- add this line
MatsimEventsReader matsimEventsReader = new MatsimEventsReader(eventsManager);
matsimEventsReader.readFile(eventsFile);
eventsManager.finishProcessing(); // <----- add this line

emissionEventWriter.closeFile();
....
```

**Comment by nkuehnel** [comment]
Thanks, @ikaddoura and @mrieser, for the explanation and help.

Adding these two lines indeed solves the issue!
