### ISSUE TITLE
should qsim automagic capacity changes end up in the output-network?

### ISSUE THREAD

**Issue by ikaddoura** [matsim-org/matsim-libs#1400]
There are several situations in which network parameters somehow don't fit together or work in combination with the qsim behavior. Sometimes the capacities provided by the network are ignored and instead a different capacity is used. This also modifies the bottlenecks in the network and of course resulting congestion patterns.
When trying to understand the congestion patterns, it's really confusing to only look at the traffic volumes and original network capacities. My use case was a network generated from OSM and qsim with kinematicWaves.

I think it would be very useful to have some kind of network which is written out which contains the "real" network parameters used by the qsim.

Of course, this can also be solved in the preparation of input files, network cleaning or similar...

**Comment by sebhoerl** [comment]
Two thoughts:
- Yes, such an output could be interesting, maybe just an optional CSV output with link and used capacities
- We could also at some point add a config switch that enables automagic / warnings by default, but optionally makes QSim throw an error as soon as something is not consistent. Then it is the duty of the modeller to fix the input data.

**Comment by kainagel** [comment]
The design principle has always been that matsim outputs what it gets as input.  The reason is that we want to avoid "drift": If you input A, matsim converts it into B, but if you input B, maybe you get C.

Especially with the network, the version that generates the warnings is often closer to the physical reality than what the qsim makes of it.  So modifying this just because we have a stupid mobsim seems the wrong way to go.

An option that I see is to additionally write the "actually used network".  This would be similar to the "experienced plans".

And yes, there could be a switch that says that the qsim should not accept networks that it has to modify.  But I think that this is, albeit related, somewhat orthogonal.

**Comment by ikaddoura** [comment]
I think after merging this pull request we can close this issue, see here: https://github.com/matsim-org/matsim-libs/pull/1414

* A bug was fixed: When using the kinematicWaves traffic dynamics, the number of lanes was always assumed to be 1.0, and thus, the flow capacity may have been reduced too strongly which may have caused too much traffic congestion! In the fixed version, the actual number of lanes is taken into consideration.
* When using the kinematicWaves traffic dynamics, there is now a switch which allows to increase the number of lanes rather than reducing the flow capacity.
* The modified flow capacity or number of lanes is written into the link attributes and will therefore show up in the output-network.
