### ISSUE TITLE
problem with maven-compiling matsim locally

### ISSUE THREAD

**Issue by kainagel** [matsim-org/matsim-libs#1446]
I am trying
```
[matsim]$ cd examples/
[examples]$ mvn clean install -DskipTests
...
```
and then
```
[matsim]$ mvn clean install -DskipTests
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------------< org.matsim:matsim >--------------------------
[INFO] Building MATSim 14.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.571 s
[INFO] Finished at: 2021-04-11T15:31:02+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project matsim: Could not resolve dependencies for project org.matsim:matsim:jar:14.0-SNAPSHOT: Failed to collect dependencies at org.matsim:matsim-examples:jar:14.0-SNAPSHOT: Failed to read artifact descriptor for org.matsim:matsim-examples:jar:14.0-SNAPSHOT: Failure to find org.matsim:matsim-all:pom:14.0-SNAPSHOT in https://dl.bintray.com/matsim/matsim was cached in the local repository, resolution will not be reattempted until the update interval of matsim has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[matsim]$ 
```
I.e. it does not find my local version of matsim-examples.  It is, however, in the .m2 directory.

I cannot say if this is newly not working, or if it never worked and only now shows up because the first instance of the missing file has not yet been deployed on the server.

Anybody has an idea what to do?  The internet says something that seems related (remove `_remote.repositories`), but that does not help.  Thanks ...

**Comment by mrieser** [comment]
I think this is the essential one:

> Failure to find org.matsim:matsim-all:pom:14.0-SNAPSHOT

The `matsim-all` pom is from the top-level.

Either do a `mvn install -DskipTests` at the top level, this installs everything once, but takes a while.

Or try **on the top-level** (outside examples) `mvn clean install -pl examples -am`.  (`-pl` = project list, `-am` = also-make required projects, i.e. matsim-all)

**Comment by mrieser** [comment]
Background story: See #1291, as well as [my comment](https://github.com/matsim-org/matsim-libs/pull/1291#issuecomment-748093727) predicting exactly that error... ;-)

**Comment by mrieser** [comment]
The first 14.0-SNAPSHOT was now automatically deployed to the new maven repository using GitHub Actions. Also, MATSim's pom.xml was modified to use the new maven repository. Thus, for anybody else now, a `cd examples; mvn clean package` should now work as well as the missing `matsim-all`-dependency should now be downloaded form the maven repository. In your case, it still looked at the old bintray repo, where it was not yet available. So it has to do with some changes made to the maven setup in MATSim, as well as unfortunate timing that there was not yet an official 14.0-SNAPSHOT available due to the maven-repo migration. I think it should not happen anymore in the future, when a potential 15.0-SNAPSHOT will be automatically be deployed once we upgrade the version number next year.
