### ISSUE TITLE
Extension search radius in SRR defaults to negative infinity

### ISSUE THREAD

**Issue by balacmi** [matsim-org/matsim-libs#1482]
Currently the extension search radius in the intermodal swiss rail router defaults to negative infinity. 

In cases where this is not set leads to an interesting behavior when there are less than 2 stops found for access/egress:

https://github.com/matsim-org/matsim-libs/blob/1cd0cd7bb65e7af9fd7abfec0bf8e61cc90acf46/matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/DefaultRaptorStopFinder.java#L166

In this case the search radius will be negative infinity and no stops will be found, even though, previously there might have been 1 stop.

I would suggest setting the default extension search radius to 0.0. What others think?

**Comment by mrieser** [comment]
The commit that added those parameters and set them to negative infinity has the following commit message:

> force users to set values in intermodalAccessEgress by config consistency checker and default at negative infinity

So it seems to have been a deliberate choice by @vsp-gleich. Maybe he can comment on this issue and explain a bit more of the reasoning, why not a useful default value was chosen.

**Comment by balacmi** [comment]
I see... 
I noticed this behavior while working on the test case for the SRR. As consistency checker is only used when there is a controller, this check was not picked up. 

Still putting the default value to 0.0 would ensure that even outside of the controller the above mentioned situation does not occur and the number of stops is maintained at 1. Consistency checker nicely checks if this value is larger than 0 so it will still work as previously intended.

**Comment by vsp-gleich** [comment]
Sorry for the late answer, our TU email infrastructure was down for 2 weeks. If I remember correctly I talked about this with @jfbischoff at the time and we had a tendency to force people to explicitly set a value here, because it is hard to come up with a value good for all access modes in all possible contexts (I implemented those search extension radii and thought of e.g. walk for access rather 300m and for car access rather several km because some stop filter applies). Obviously there is now a tendency back towards a "reasonable" default. Now it's open to discussion what a reasonable default would be here, I guess definitely something larger than 0. Using 0 instead of negative infinity avoids finding no stops, but then it's not clear if this is an advantage (works out of the box) or a disadvantage (it's still wrong and nobody will notice).
So maybe 0 is as wrong as negative infinity here, so I'm not against it. Maybe knowing the use case which bypasses the config consistency checker helps to understand what is best.

**Comment by vsp-gleich** [comment]
Ok, tests are something where we can expect some experienced developer from one of our groups, but using the router outside of controller could also be done by someone with intermediate matsim knowledge. Since the negative infinity extension radius only gives 0 stops if no stop was found in the initial search radius before, this is not a consistent failure which can nudge the user to set an extension radius. So I'm fine with using 0 as a default, 0 seems less harmful.

**Comment by balacmi** [comment]
OK, great, I will make a pull request.
