### ISSUE TITLE
Put CRS info directly into XML files

### ISSUE THREAD

**Issue by phaj19** [matsim-org/matsim-libs#1513]
Hi,
this is bugging me for a longer time, but now I found the courage to ask - why is the CRS (Coordinate Reference System) information always supplied externally instead of being part of the XML files that have any kind of spatial data, namely network, facilities, plans, transit data?
I know you can set the CRS globally in the config for the simulation, but:
1) That does not help if you run some pre- or post- processing script where you do not want to load the whole config. There are even lots of cases that have the wrong CRS hardcoded and I need to copy the whole class just to change the CRS.
2) If you find some ancient file and wonder what CRS it could be.

In general, it would make sense to me to put the file-related attributes directly to the XML.

I understand there would be some work:
API would need to be adjusted to contain functionality like network.getCRS()
Backward compatibility would need to be ensured by keeping the options in config, but the implicit data could have priority.
WGS84 should be prevented for simulation runs (Euclidean maths)

Still, this would be a way to use the potential of the XML files to their fullest.

**Comment by kainagel** [comment]
Glad you asked.  You can set the CRS in each of the files; the syntax is something like 
```
...
<network>
   <attributes>
      <attribute name="coordinateReferenceSystem" class="java.lang.String">EPSG:31468</attribute>
   </attributes>
...
```
This not only works for the network files but for most other files that use a CRS.

There are some helper methods in `ProjectionUtils`.  `ProjectionUtils.getCRS( network )` should return a string with the CRS.

We decided to do it via the attributes since this is something we already have in place.  It is maybe less nice than something that is fully typed, but in this way it was possible to add it without having to bump up the dtd version.

See Section 2.2.3.3 in the MATSim user guide https://www.matsim.org/docs/userguide/ .

Setting it in the config was older, and we just left it there.

Please let us know if there remain open questions (but please have a look in the user guide first :-) ).

**Comment by phaj19** [comment]
I stand corrected and I am happy to see that it is already implemented :-)
I started with Matsim around 2017, so this is some feature that somehow slipped undetected.
