### ISSUE TITLE
Undefined Time crashes the simulation

### ISSUE THREAD

**Issue by phaj19** [matsim-org/matsim-libs#1588]
https://github.com/matsim-org/matsim-libs/blob/e71b39d3c1f25a6883aedebba7f4ecda0c5c3782/contribs/socnetsim/src/main/java/org/matsim/contrib/socnetsim/framework/replanning/modules/BlackListedTimeAllocationMutator.java#L100
I guess this line expects the time to be undefined sometimes?

**Comment by Janekdererste** [comment]
Looks like it. If you provide more information to your problem somebody might be able to help.

**Comment by tschlenther** [comment]
looks like there is a `!` missing. Obviously, one can only derive the time in seconds from the `OptionalTime` object when it ### is defined

**Comment by JWJoubert** [comment]
@phaj19, I think that might be an artefact (in fact, a mistake) of code refactoring, especially because it is in a contrib - it probably got overlooked. I agree with @tschlenther - there is just a `!` missing. The concept of `Time` being either _defined_ or _undefined_ is fairly new. It used to be dealt with inconsistently, some make _undefined time_ 'Double.NEGATIVE_INFINITY', some `0`, some `Double.NaN` and some `null`. So this was a _good_ move, but in your case, there is likely not someone actively looking after the `socnetsim` contrib... or it simply got missed.

**Comment by Janekdererste** [comment]
> looks like there is a ! missing. Obviously, one can only derive the time in seconds from the OptionalTime object when it ### is defined

Didn't see this detaul. I'm very sorry @phaj19

**Comment by Janekdererste** [comment]
> but in your case, there is likely not someone actively looking after the socnetsim contrib

If this is something you need, you could create a pull request with a fix. You can add me as a reviewer and I'll merge it for you (don't really know what the requirements for contributing are)

**Comment by JWJoubert** [comment]
> ...you could create a pull request with a fix. You can add me as a reviewer and I'll merge it for you (don't really know what the requirements for contributing are)

I thought of just fixing it for you, @phaj19, and creating the pull request. But, I am afraid, I do not have the context of what _should happen_, because the comment _just before the line_  is quite clear:
```
// do not do anything if time is undefined
if ( time.isUndefined() ) return time.seconds();
```

So, fixing it to either
```
if ( ! time.isUndefined() ) return time.seconds();
```
or 
```
if ( time.isDefined() ) return time.seconds();
```

will both be going against the _intent_ of whoever wrote the initial functionality. Sorry, but I do not know what that intent it/was.

**Comment by tschlenther** [comment]
maybe the method should return an `OptionalTime`. It reads like that nothing should happen within `mutateTime` if `time.IsUndefined()`. So `mutateTime` could return an `OptionalTime` that has either a mutated value or is (still) undefined
