### ISSUE TITLE
Multithreading / Race-Condition in Scoring functions with arbitrary events

### ISSUE THREAD

**Issue by mrieser** [matsim-org/matsim-libs#1593]
The current `ScoringFunction` interface offers a method `handleEvent(Event)` to handle arbitrary (person) events in the scoring function. But there is a problem when using this in combination with the other `handleLeg()` and `handleActivity()` methods.

`handleLeg()` and `handleActivity()` of a scoring function get called from `ScoringFunctionByPopulation`, which registers itself as a listener to `EventsToActivities` and `EventsToLegs` to forward the corresponding `handleLeg`- and `handleActivity`-calls.  `EventsToActivities` and `EventsToLegs` are managed by `EventsToLegsAndActivities`, which is itself an event handler that handles the corresponding events.

`handleEvent(Event)` of a scoring function gets called from `ScoringFunctionByPopulation`, which registers itself as an EventHandler to filter out the corresponding events.

This means, we have two event handlers: `ScoringFunctionByPopulation` and `EventsToLegsAndActivities`. With parallel events handling, they run in different threads, and thus may process events with varying delay. But at the end, a single scoring function object can be called by both event handlers independently, resulting in multithreading issues (e.g. visibility of memory changes) and race-conditions (person events may arrive too late compared to handleAct- and handleLeg-calls).

This leads to numerous problems to ScoringFunctions that actually want to use the arbitrary events for some custom logic.

---

How can this fixed? A scoring function must not be called from two different threads, in my opinion.

I had a similar problem a while back when implementing TripScoring: At that time, `EventsToLegs` and `EventsToActivities` were two different event handlers in two different threads, and thus activities and legs did not necessarily show up in the right order. This was fixed by introducing `EventsToLegsAndActivities`.

It would be best if `ScoringFunctionByPopulation` would include the functionality of `EventsToLegs` and `EventsToActivities` in itself, so it is a single event handler responsible for scoring. But as `EventsToLegs` and `EventsToActivities` are also used outside the scoring function, this would either result in a mix of responsibility, or in duplicated work, as `ScoringFunctionByPopulation` as well as `EventsToLegsAndActivities` both perform the same task.

Any opinions or other ideas?

**Comment by rakow** [comment]
I can only agree with you that it would be best if a single event handler is responsible for the scoring. I was not aware of this implementation detail, and probably others will unknowingly run into similar problems.

**Comment by kainagel** [comment]
This used to be just a pure events handler.  MZ changed it so that there were separate methods for Legs and Activities (and, by Marcel, Trips), with the thought that that would be "closer to the real meaning" for implementers.  However, I have to say that this always caused problems, for example because of the wrap-around activity, and because of the "general" events channel which was needed to deal with information that does not go into Activities or Legs (e.g. the money handler).

So one option might be to go back to the old design: There would only be one event handler per agent, and users need to make sure that their plugin is according to specs.  In terms of implementation, that feels much simpler than the current design.

(It would still not be a completely normal events handler, since we cannot pass all events to all agents.  But it could be a lot closer.)

**Comment by Janekdererste** [comment]
I ran into a similar (or the same issue) when I was playing with a custom events manager. The scoring stuff assumes to be called by a single threaded event handler. Which makes the implementation of our events managers more complicated I think because they distinguish between a parallel and a single threaded phase. At least ```SimStepParallelEventsManagerImpl``` does.  

Would this be fixed by the proposed improvement? Probably it is not important performance wise, but this is a hidden assumption of how event managers work internally. 

Hope this comment is not totally un-related.

**Comment by mrieser** [comment]
@Janekdererste 
> The scoring stuff assumes to be called by a single threaded event handler. 

I'm not sure I understand your comment. To my knowledge, every EventHandler in MATSim should be called from a single thread only. This was decided a very long time ago to facilitate implementations of event handlers. Otherwise, each and every event handler would need to make sure it correctly works in multithreaded environments, dealing with data visibility, cache updates, race conditions etc. As this is rather difficult to get right for many programmers, it was decided that EventHandlers can assume to be called from one thread only.

The problem at hand with the scoring function is exactly that it is **not** called from a single thread, but from two different threads actually, leading to hard-to-debug and hard-to-handle concurrency issues (once directly as `ScoringFunctionsForPopulation` is a registered event handler, and once as the aforementioned class is registered as handler for `handleLeg` and `handleActivity` which is called from `EventsToLegsAndActivities` which is itself a different registered event handler).

So it might make the implementation of an `EventsManager` more complicated, as the events manager has to deal with the threading details, but thanks to this all the different event handlers do not have to deal with it.
