### ISSUE TITLE
Support for multiple different road pricing schemes in a single Road Pricing config

### ISSUE THREAD

**Issue by mfitz** [matsim-org/matsim-libs#1855]
Hi

[These docs ](https://www.matsim.org/apidocs/roadpricing/12.0/org/matsim/contrib/roadpricing/package-summary.html) make it clear that the road pricing contribution can support only a single road pricing scheme type per simulation. I was wondering what would need to change in the RP implementation to introduce support for multiple schemes. Would it require a fundamental change to the package, or is there a more straightforward change that could give us this ability? Is there a relatively simple way for us to do this ourselves?

**Comment by kainagel** [comment]
Depends on what you need.  You can set an individual toll per link, and with that you can, in fact, emulate lots of other things.  E.g. setting the toll only to cordon links would emulate a cordon toll.  Setting the toll proportional to the length of the link would emulate a distance toll.  Evidently, for the first two there are also special setting, but they are not strictly speaking necessary.  

What can _not_ be emulated in this way is an area toll, i.e. a flat rate once one starts moving a vehicle inside an area (as in London).  However, area tolls are tricky anyways, since it is not possible to decide on a per-trip basis if it is worth to pay the flat fee.

**Comment by mfitz** [comment]
Thanks @kainagel , we've been able to do what we need using tolls per link, so I'm closing this issue now.
