### ISSUE TITLE
Travel time observation: discretization issue

### ISSUE THREAD

**Issue by luchengqi7** [matsim-org/matsim-libs#1933]
Hi @mrieser, I have a small question regarding the travel time observation script. For links that are not used by any vehicle (of the mode), the travel time observation is returning the raw values (lengh/free speed) of the free speed travel time. I think it may be a good idea if we update this so that it match the Qsim discrete time step (see QsimFreeSpeedTravelTime). 

https://github.com/matsim-org/matsim-libs/blob/e28f17a6df119222dd4dc0af81dae5f84008a090/matsim/src/main/java/org/matsim/core/trafficmonitoring/TravelTimeDataArray.java#L115

**Comment by luchengqi7** [comment]
@michalmac I think this is the reason for the fluctuation in the routing of DRT between different iterations. As the unused links are getting shorter travel time (i.e., without any rouding up). The travel time are then changing constantly because of the travel time estimation alpha, even though we set the capcity to a very large value.

**Comment by sebhoerl** [comment]
@luchengqi7 I think we already had this discussion a while ago. This also becomes relevant if we, for instance, want to see if a predicted travel time (in the discrete mode choice model) reflects well the experienced travel time afterwards. I think Kai's position was to leave it as is (because it will introduce a lot of linked effects, as you seem to see in your PR) and only adjust it for specific scenarios when we need this to be consistent specifically. Then you can simply use the QSimFreeSpeedTravelTime as is used already in the DVRP/DRT benchmarks, I think. Not sure if anything has changed regarding this topic :-)

**Comment by sebhoerl** [comment]
What is true is that we might fix the fact that the "baseline" travel time is hardcoded in  `TravelTimeDataArray.java`. It should probably use the currently bound `TravelTime` for the specific modes?

**Comment by michalmac** [comment]
As @sebhoerl already mentioned, this is the way we ran dvrp benchmarks in the past: https://github.com/matsim-org/matsim-libs/blob/63284a47c5e99d86d21094ee97b65bba3c6ea722/contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/benchmark/DvrpBenchmarks.java#L41

This ensures you will always get the same estimated TT values in every iteration.

BTW. You can also read them from an output of an existing simulation instead of going for `QSimFreeSpeedTravelTime`.

**Comment by michalmac** [comment]
Regarding this line:
https://github.com/matsim-org/matsim-libs/blob/e28f17a6df119222dd4dc0af81dae5f84008a090/matsim/src/main/java/org/matsim/core/trafficmonitoring/TravelTimeDataArray.java#L115

- IMO I do not think that we need to be super exact (down to a single second). In the end, there may be different mobsim implementations and each may work a bit different here.
- Would be good to be more less exact when it comes to computing that value for different (mobsim) modes in the case **when** we assume separate TT calculators for each mode, e.g. a 15 m/s free-flow speed is not the best value you can think of for a bike. This is aligned with this comment https://github.com/matsim-org/matsim-libs/issues/1933#issuecomment-1091605338

**Comment by luchengqi7** [comment]
Thanks a lot for your input! I will use the DRT benchmark inding to solve for the flucutaion problem in the DRT service.

Perhaps, it is also a good idea to introduce what I have found in the DRT study (just for your information). I am using a network with enlarged capcity (x10000). I have observed flutaion in the waiting time for **more than 100s** between iterations. And since in my DRT project, arrival time of the requests is one of the important facotr, the difference between estimated travel time and the actual travel time can make the reqeust a "good one" or a "late arrival". Actually, I am constantly getting late arrival (around 5%) even with very large fleet sizes.

**Comment by luchengqi7** [comment]
> As @sebhoerl already mentioned, this is the way we ran dvrp benchmarks in the past:
> 
> https://github.com/matsim-org/matsim-libs/blob/63284a47c5e99d86d21094ee97b65bba3c6ea722/contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/benchmark/DvrpBenchmarks.java#L41
> 
> This ensures you will always get the same estimated TT values in every iteration.
> 
> BTW. You can also read them from an output of an existing simulation instead of going for `QSimFreeSpeedTravelTime`.

Yeah, I will proably do that for the "pseudo loaded network case". But I guess, for a more accurate estimation of the travel time, I guess I should write a new travel time estimator/recorder.
