### ISSUE TITLE
DRT request submission is always 1 second earlier than in the plans

### ISSUE THREAD

**Issue by luchengqi7** [matsim-org/matsim-libs#2112]
The drt submission event happens 1 second earlier than in the population file (see figures below). 

![plans](https://user-images.githubusercontent.com/43133404/181048323-de372c90-1d9a-4c9d-b4a1-0d1f827712eb.png)
![events](https://user-images.githubusercontent.com/43133404/181048348-a3c98881-6762-4723-9f9c-9bae4534a8cf.png)

**Comment by michalmac** [comment]
Thanks for reporting. It looks like the "drt interaction" is planned to take 1 second (due to 1 second typically spent the switching between leg and activity):
https://github.com/matsim-org/matsim-libs/blob/acd8bbb9d557304bd3a1b3061bd6536230d3efb2/contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpRoutingModule.java#L115-L116

However, this is not the case for zero-duration activities. They are concluded immediately. I will fix this.
