### ISSUE TITLE
Capped fare - public transport 

### ISSUE THREAD

**Issue by gac55** [matsim-org/matsim-libs#2141]
Many fare policies are being proposed to help persuade people to mode shift to public transport.

MATSim currently supports a distance or time based cost for public transport. This is something we therefore estimate and calibrate, based on some fare based data and a travel survey, for example. We are able to proxy fare reductions via this parameter and run scenarios.

The MATSim SBB implementation has enabled us to further subdivide modes so that we can better break up public transport, for example into local bus, high speed rail etc.

One policy that is hard to implement in this method is a fare cap. In this case the agents may pay up to a certain amount, then cap out and any subsequent travel is free. 

Before we begin to test implementations, has someone tried something like this before? 

Many thanks

**Comment by JWJoubert** [comment]
Hi @gac55, we have tried it, not  in public transport fare, but in road pricing scenarios. I do believe that the principle would be the same, though. You will just have to implement your own event listener which keeps track of each agent's _tally_ of total fare spent. Since MATSim typically runs only for 24 hours, and fare caps (like road pricing) is capped on monthly spent, you will have to live with the assumption that the daily cap (x / 22.5, or whatever the average working days per month are in your scenario) is a fixed portion of the monthly cap.

Every boarding event then checks a person's total fare tally, and only if it has not been reached, a `PersonMoneyEvent` is thrown.

**Comment by JWJoubert** [comment]
> You will just have to implement your own event listener which keeps track of each agent's tally of total fare spent. 

This might be as simple as a `Map<Id<Person>, Double>` in your class.

**Comment by gac55** [comment]
Thanks @JWJoubert . We employed this approach for capped road pricing too ;) Based on your advice then! 
We will investigate this avenue further, thank you.
