### ISSUE TITLE
Reading DRT config group when companions module present

### ISSUE THREAD

**Issue by luchengqi7** [matsim-org/matsim-libs#2717]
Hello, 

Currently, the DRT companion module writes something in the output config (within DrtConfigGroup). Because of that, I am experiencing problems when reading the DrtConfigGroup (e.g., during post-analysis process):
**Unsupported parameter set type (companions)**

Since this parameter set is within the DRT config group, we cannot directly specify it as a custom module when loading the config. Therefore, it seems that we are writing something that cannot be read by MATSim into output config. 

Maybe we should fix this problem. Or maybe there are already solutions? 

Thanks!

**Comment by steffenaxer** [comment]
When you have the **companions** parameter in your config you obviously have used them from the drt-extension contrib. While loading the config from XML you need to tell the MultiModeDrtConfigGroup that there are now new, so called optional paramters, that have been used by you. This is done with the provided code snipped. 

**Please load your config as follows:**
`Config config = ConfigUtils.loadConfig("configPath", new MultiModeDrtConfigGroup(DrtWithExtensionsConfigGroup::new));`

To avoid this problem in the future one cloud provide default Supplier<DrtConfigGroup> within the MultiModeDrtConfigGroup constructor so that at least all paramter extensions from the drt-extension contrib coud be loaded vanilla. However, it might be that you have some custom paramter extensions. In this case you will always need the provided code line.

**Comment by luchengqi7** [comment]
Hi Steffen, that works! Thank you very much! 

And thanks for the suggestion!
