### ISSUE TITLE
Calibrating Access/Egress mode for pt mode using Discrete Choice Module?

### ISSUE THREAD

**Issue by synas34** [matsim-org/matsim-libs#3097]
As in the subject I am wondering how I can fix Access/Egress mode for pt using existing Discrete Choice Module?

Could I define seperate pt modes such as pt-walk, pt-bike, etc. in my TripEstimator, and have the transit routes be able to accomodate all those modes?

Is there a way to calibrate SwissRailRaptor to take this parameters? I am trying to make changes to [DefaultRaptorIntermodalAccessEgress ](https://github.com/matsim-org/matsim-libs/blob/f293d1bc65107aeda637ee55d659f5baa0151ef4/matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/DefaultRaptorIntermodalAccessEgress.java#L26) but it seems to not have the same effect as through TripEstimators.

Any advice on how to calibrate Access/Egress walk, bike, and drt modes for pt mode using DCM would be greately appreciated.

Thank you, 
Nasir

**Comment by sebhoerl** [comment]
Hi, usually we don't use the intermodal functionality of SRR when we do intermodal simulations with DCM. Because SRR defines its own choice process, which is not compatible with the logic of a multinomial-logic model (as you say, one would need to fix a mode). So what we usually do is to define a composite `RoutingModule` that finds a stop for each trip that we want to use and then we delegate the part from the origin to the stop to the first routing module (walk, bike, drt, whatever) and then we route the rest to the egress stop by the transit `RoutingModule`. This resembles pretty much the logic from the DRT contrib. We have code for that somewhere in the eqasim repository and we were planning to package this up cleanly, but we didn't find time to do so yet. 

Note that from a DCM perspective PT + different access modes are probably correlated alternatives, so the error terms should be correlated or one should probably used something like a Nested Logit Model.
