### ISSUE TITLE
How to create a plans file based on my network file in MATSim

### ISSUE THREAD

**Issue by MarcinKinque** [matsim-org/matsim-libs#3502]
Hello guys,

I am new here and trying to use MATSim, but I have several problems.
First of all:

- I downloaded the "Stand-Alone GUI of MATSim." Is it true that I just have to select my config file and my output path to run the simulation?

- I have a pretty good network file, but how can I create a plans file for it? Is there a tool where I can set the population, the age of the people, etc., and it creates a plans file that fits with the network file? I'm pretty lost and would appreciate any help...

**Comment by Janekdererste** [comment]
The [matsim user guide](https://matsim.org/files/book/partOne-latest.pdf) is a good starting point. Also, we have a tutorial on our [website](https://matsim.org/docs/). 

 > Is it true that I just have to select my config file and my output path to run the simulation?
 
 If you want to run matsim using a GUI, you can select any config file from the gui and run your scenario with it. 

> Is there a tool where I can set the population, the age of the people, etc., and it creates a plans file that fits with the network file?

In general no. You have to create the demand for the simulation yourself. Possible data sources for this are mobile phone trajectories, traffic diaries or commuter statistics. [Here](https://github.com/matsim-org/matsim-code-examples/tree/2024.x/src/main/java/org/matsim/codeexamples/population) are some examples for creating a population. 

Our general issue tracker for these kinds of questions is located in the [matsim-code-examples](https://github.com/matsim-org/matsim-code-examples) project. Please refer to that tracker, if you have more questions. I am closing this issue here, because we keep track of internal issues here.
