### ISSUE TITLE
Latest MATSim release -- docs/github need updating

### ISSUE THREAD

**Issue by billyc** [matsim-org/matsim-libs#905]
The matsim website says the latest release of MATSIM is 0.10.1, released August 2018:
https://matsim.org/downloads

And also here on Github, the latest release is MATSim 0.10.1:
https://github.com/matsim-org/matsim-libs/releases

I think we're at least on version 11 and have been for a while now right?

Someone should probably create a new release and also update the website to point to it.

**Comment by kainagel** [comment]
Strange.  Jakub, könntest Du Dir das bitte nochmal anschauen?  Irgendetwas haben wir in unserem release process wohl übersehen.

Danke & viele Grüße

Kai

On 3. Mar 2020, at 12:40, Billy Charlton <notifications@github.com<mailto:notifications@github.com>> wrote:


The matsim website says the latest release of MATSIM is 0.10.1, released August 2018:
https://matsim.org/downloads<http://quarantine.tu-berlin.de:32224/?dmVyPTEuMDAxJiZlMTJmOGRmMTE5ODRmZDkyMj01RTVFNDI0MF84OTUwXzE1NDU2XzEmJjkyZWUxZWU4MzUxNTFkYz0xMjMyJiZ1cmw9aHR0cHMlM0ElMkYlMkZtYXRzaW0lMkVvcmclMkZkb3dubG9hZHM=>

And also here on Github, the latest release is MATSim 0.10.1:
https://github.com/matsim-org/matsim-libs/releases<http://quarantine.tu-berlin.de:32224/?dmVyPTEuMDAxJiZlNjM2ZDZlYzBiY2FhMWQ0Mj01RTVFNDI0MF84OTUwXzE1NDU2XzEmJjk2MmZhZWY4ZDEzMTJkMj0xMjMyJiZ1cmw9aHR0cHMlM0ElMkYlMkZnaXRodWIlMkVjb20lMkZtYXRzaW0tb3JnJTJGbWF0c2ltLWxpYnMlMkZyZWxlYXNlcw==>

I think we're at least on version 11 and have been for a while now right?

Someone should probably create a new release and also update the website to point to it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<http://quarantine.tu-berlin.de:32224/?dmVyPTEuMDAxJiZlNjM2ZDZlYzBiY2FhMWQ0Mj01RTVFNDI0MF84OTUwXzE1NDU2XzEmJjk2MmZhZWY4ZDEzMTJkMj0xMjMyJiZ1cmw9aHR0cHMlM0ElMkYlMkZnaXRodWIlMkVjb20lMkZtYXRzaW0tb3JnJTJGbWF0c2ltLWxpYnMlMkZpc3N1ZXMlMkY5MDUlM0ZlbWFpbCU1RnNvdXJjZSUzRG5vdGlmaWNhdGlvbnMlMjZhbXAlM0JlbWFpbCU1RnRva2VuJTNEQUNDNjdNT1Y1NFgzR0g3TU9EV0NPT0RSRlRVRDdBNUNORlNNNExBSVREUEtZWTNQTlZXV0szVFVMNTJIUzRERlVWRVhHNDNWTVdWR0czM05OVlNXNDVDN05GU000SVI3MlRXUQ==>, or unsubscribe<http://quarantine.tu-berlin.de:32224/?dmVyPTEuMDAxJiZlNjM2ZDZlZjA1Y2FiYmRiMj01RTVFNDI0MF84OTUwXzE1NDU2XzEmJmQyY2Y0ZTk4MzUzMTFjMD0xMjMyJiZ1cmw9aHR0cHMlM0ElMkYlMkZnaXRodWIlMkVjb20lMkZub3RpZmljYXRpb25zJTJGdW5zdWJzY3JpYmUtYXV0aCUyRkFDQzY3TU1CSElCMk43NFdYNjJVR1VUUkZUVUQ3QU5DTkZTTTRMQUlURFBB>.

======================================================

MATSim User Meeting 6/Apr/2020 in Warsaw https://matsim.org/conferences/user_meeting_2020

Clone github.com/matsim-org/matsim-example-project<http://github.com/matsim-org/matsim-example-project> to get started.
Also see github.com/matsim-org/matsim-code-examples<http://github.com/matsim-org/matsim-code-examples> | matsim.org/downloads<http://matsim.org/downloads> | matsim.org/docs/tutorials<http://matsim.org/docs/tutorials> | matsim.org/open-scenario-data<http://matsim.org/open-scenario-data> | matsim.org/faq<http://matsim.org/faq> .

---
www.vsp.tu-berlin.de<http://www.vsp.tu-berlin.de> +49 30 314 23308 (phone) +49 30 314 26269 (fax)
postal: TU Berlin Sekr. SG 12, Salzufer 17-19, 10587 Berlin
physical: building SG 4.1, room 305

**Comment by mrieser** [comment]
it's probably because the 11.0 was the "spring-release for teaching", and you expected that there will be a "11.1" release in summer after teaching that should be announced more widely. But that 11.1 never happened, likely because 11.0 was stable enough.

**Comment by josiekre** [comment]
@billyc Pretty sure this can be closed now. Was looking around for something else related to the newest 12.0 release.
