### ISSUE TITLE
Matsim weekly build 2020-09 failed

### ISSUE THREAD

**Issue by vsp-gleich** [matsim-org/matsim-libs#908]
The latest matsim weekly release build failed:
[https://oss.jfrog.org/artifactory/simple/oss-snapshot-local/org/matsim/matsim/](https://oss.jfrog.org/artifactory/simple/oss-snapshot-local/org/matsim/matsim/)
[http://ci.matsim.org:8080/](http://ci.matsim.org:8080/)
A test in taxi failed with no obvious reason. Travis managed to build matsim and passed all tests.

**Comment by mrieser** [comment]
there is something in all these taxi/drt/dvrp tests that crashes the JVM on the Jenkins-Server. We already had to ignore some other tests to get the normal builds pass on Jenkins, but couldn't figure out what the problem was.
I currently suspect a wrong native dependency of the JVM (think of something like freetype, glibc or similar), as the hard JVM crashes happen with a variety of Java 11 versions.

**Comment by tschlenther** [comment]
this issue still seems to up-to-date, could somebody please fix this?

**Comment by kainagel** [comment]
These things are enormously time-consuming to debug, and I guess nobody has time for this right now :-(.

The logs of the last (possibly failed) runs are here: http://ci.matsim.org:8080/job/Weekly%20Builds/ws/matsim/contribs/taxi/target/failsafe-reports/ .  

The log of the failed test is here: http://ci.matsim.org:8080/job/Weekly%20Builds/ws/matsim/contribs/taxi/target/failsafe-reports/org.matsim.contrib.etaxi.run.RunETaxiScenarioIT-output.txt .  It is not overly helpful, except that it crashes in the middle of the qsim.

Here is something else: http://ci.matsim.org:8080/job/Weekly%20Builds/ws/matsim/contribs/taxi/target/failsafe-reports/2020-03-23T21-03-48_353-jvmRun1.dumpstream/*view*/ .  It reads a bit like it is trying to process a stacktrace, and failing.  If that is the correct interpretation (of which I am not sure), then this could be the reason why we are not getting a reasonable error message.  

@tschlenther : If you want to help, could you please discuss with @mrieser what could be done?  One option, in my view, would be to switch the taxi contrib off in the maven build and see if that helps (for the weekly release), and then decide what may follow.

**Comment by tschlenther** [comment]
could this be related to more restrictions on reflection?
at least in http://ci.matsim.org:8080/job/Weekly%20Builds/ws/matsim/contribs/taxi/target/failsafe-reports/2020-03-23T21-03-48_353.dumpstream
it says something about illegal reflective access as well as the following:

> WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1

@Janekdererste we spoke about changes related to reflection coming with the java update, do you maybe have an idea?

@mrieser i am happy to help, please let me know what i can do

**Comment by tschlenther** [comment]
only for protocol:
@jwilk79 suspected it could be related to the surefire plugin version or the parameters, with referring to the follwing warning:

> [WARNING] The parameter forkMode is deprecated since version 2.14. Use forkCount and reuseForks instead.

but as far as i can see, the taxi has no configuration for the surefire plugin in it's pom.
In comparison, the minibus contrib does.

**Comment by michalmac** [comment]
I had some issues with surefire/failsafe plugins in the past. Sometimes changing some parameters would help. But this issue is hard for me to debug, as it happens only on jenkins (and not necessarily in all build pipelines) and the response time is long...

For the time being, I will remove these tests (or replace them with something smaller in size.)

**Comment by kainagel** [comment]
Might be worth trying.  There are two things:

1. The tests can be run in a way that each test class or even each test method runs in a separate JVM.  Safer, but slower.  Since it is slower, we try to avoid it.  However, there is probably no harm to switch it on for contribs with mostly integration tests.  Might be worth trying.  (As a note: nonfinal static variables cause problems with the "faster" version.)
2. Once we understand the concept, we need to find the right config switches.  This has changed in maven, and since we have recently changed our maven version, it makes sense that the "correct" config switches are different now.  I have normally tried to put both variants into the pom.xml so that we should get warnings but it should still do the right thing.  Clearly, since we are now decidedly on the new maven version, the old syntax can be commented out and eventually deleted.  https://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html for syntax hints.  Normally we try to re-use JVMs as much as we can; for the taxi contrib, we might now want to set the switches into the other direction.

**Comment by tschlenther** [comment]
if i understand it correctly, the reuse of a JVM already is avoided by

`<reuseForks>true</reuseForks>`

in the taxi pom. But we only use one fork..

**Comment by mrieser** [comment]
I had to disable some tests during the code sprint as they crashed the JVM. Looks like some Integration Tests do this as well.
I tried with different JVM versions, it crashed on all of the ones I tried, even with the reference implementation. To me, it looks as if there is a problem or incompatibility between the JVM and some native library installed on the system that results in the SegFault. At least, this would explain why it only happens on this one system, and why it happens with different JVMs. But that doesn't make it easier to debug...

**Comment by mrieser** [comment]
might be a (windows exe) manifest thing: https://issues.apache.org/jira/browse/NETBEANS-1227. If the problem indeed only occurs with the executable, then I'll have to figure out how to edit this manifest and how to include it into the build...

**Comment by Janekdererste** [comment]
> could this be related to more restrictions on reflection?

I don't think this is related to the more restrictive reflection rules in Java > 9. So far this only causes warnings but no errors.

**Comment by mrieser** [comment]
It finally ran through again: http://ci.matsim.org:8080/job/Weekly%20Builds/108/
Thanks to everybody who helped get it up and running again!

**Comment by vsp-gleich** [comment]
Thank you all :+1:!
