### ISSUE TITLE
Drt interaction activities have arbitrary durations

### ISSUE THREAD

**Issue by tschlenther** [matsim-org/matsim-libs#917]
Drt interaction activities seem to be of arbitrary duration. This only concerns drt interaction activities after getting off the vehicle (i.e. after the dropoff). The BusStop activity duration for the driver is fine, just as the activity duration of customer's the interaction activity before the leg.

I checked the following things:
1) During routing before the sim, everything looks fine. The generated plans are consistent and do not show strange durations.
2) The new ScheduleTimingUpdater also does not have anything to do with this

The problem occurs in a newly created equil test scenario as well as when running the examples in matsim-maas.

**Comment by vsp-gleich** [comment]
For some strange reason we have not found such overlong interaction activities in pure drt trips or intermodal pt+drt trips in matsim-berlin avoev runs of last week. But they definitely did occur in  [matsim-maas](https://github.com/matsim-org/matsim-maas/blob/master/src/main/java/org/matsim/maas/drt/RunStopBasedDrtExample.java)

**Comment by tschlenther** [comment]
The problem also persists when setting
        `config.plans().setActivityDurationInterpretation(PlansConfigGroup.ActivityDurationInterpretation.minOfDurationAndEndTime)`

**Comment by vsp-gleich** [comment]
IMHO this problem is likely to also affect other stage activity types (e.g. `pt interaction`.

I ran [https://github.com/matsim-org/matsim-maas/blob/master/src/main/java/org/matsim/maas/drt/RunStopBasedDrtExample.java](https://github.com/matsim-org/matsim-maas/blob/master/src/main/java/org/matsim/maas/drt/RunStopBasedDrtExample.java) with different matsim weekly releases and checked the `drt interaction` activity start and end time in the events file for a specific agent (the second drt interaction activity (after the drt leg) of agent 12052000_12052000_100).

- The activity duration is 0 as expected until matsim-12.0-2020w07 (I also checked 2020w06 and 2020w02, the latter was used in the not affected matsim-berlin avoev runs).

- In matsim-12.0-2020w08 and 12.0-SNAPSHOT the problem occurs.

**Comment by vsp-gleich** [comment]
IMHO this is a bug, because it worked correctly before (using an identical config). #918 is a temporary work-around until this issue here is fixed.

**Comment by kainagel** [comment]
(1) It should not depend on that switch.  Interaction activities should be created such that this works in all cases.

(2) The following lines are currently in `SwissRailRaptorRoutingModule`:
https://github.com/matsim-org/matsim-libs/blob/bc60f792213ef0ef057e0962250696569caff3ed/matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorRoutingModule.java#L69-L75
They do not correspond to the specification of interaction activities; interaction activities should have duration zero and undefined start and end time.

This is also not Marcel's original code.  Maybe the changes were moved in with the change from `double` to `OptionalDouble` of the activity times?

Could someone please change this back?  It is, as usual, a bit surprising that no test caught this.  

Also, we probably need to look for all other places where interaction activities are generated.

We should probably consider a centralized static method `createInteractionActivity(...)`.  There is an approximation to such a method in `NetworkRoutingInclAccessEgressModule`; maybe use that.  But one should presumably pass `mode` and not the stage activity type.

Thanks ...

**Comment by vsp-gleich** [comment]
Not setting start and end time fixed it for drt interaction activities.

I started work on centralizing stage activity creation in PopulationFactoryImpl (branch fixInteractionActivities).
However, it turns out that at some places we want to create stage activities, but neither have a population object nor the PopualtionFactory. This is where currently e.g. PopulationUtils.createActivityFromCoordAndLinkId() is used (e.g. in `SwissRailRaptorRoutingModule`). I continue using PopulationUtils instead of PopualtionFactory to create those stage activities.

In EvNetworkRoutingModule there is an example where only passing the mode to PopulationUtils.createStageActivity... is not sufficient, because its stage activity type is "mode charging interaction" and not only "mode interaction", so it is not clear whether individual modules should define their stage activity type(s!) or all should pass through a central method to create stahe activity types based on the mode.

**Comment by kainagel** [comment]
Thank you so much.

Maybe it is not "mode" but "prefix".

**Comment by vsp-gleich** [comment]
> We should probably consider a centralized static method createInteractionActivity(...). There is an approximation to such a method in NetworkRoutingInclAccessEgressModule; maybe use that. But one should presumably pass mode and not the stage activity type. (And in principle we need to pass the factory, or finally forget about factories for our data model.)

I'm now working on centralizing stage activity creation in `PopulationUtils.createStageActivityFromCoordLinkIdAndModePrefix` on branch centralizeStageActivityCreation. How shall we handle missing coordinates or links? Different methods (similar to the current `createActivityFromLinkId`, `createActivityFromCoord` and `createActivityFromCoordAndLinkId` methods)? Or just passing null when coord is missing?

**Comment by vsp-gleich** [comment]
> How shall we handle missing coordinates or links? Different methods (similar to the current `createActivityFromLinkId`, `createActivityFromCoord` and `createActivityFromCoordAndLinkId` methods)? Or just passing null when coord is missing?

for now just passing null
