### ISSUE TITLE
Calculation of departure times in PlanRouter

### ISSUE THREAD

**Issue by sebhoerl** [matsim-org/matsim-libs#929]
I observed a potential problem in the `PlanRouter` when the departure times for the routing are calculated.

Assume the plan:
```
     Activity (end time 08:00)
     Leg (duration 00:05)
     Activity (end time 09:00)
     Leg (duration 00:05)
     Activity (end time 10:00, duration 00:10)
     Leg
     Activity
```

With a value for `ActivityDurationInterpretation` of `tryEndTimeThenDuration` the calculation is easy: The first leg starts at 08:00 and the second leg has departure time 09:00 and the third 10:00.

Now with `minOfDurationAndEndTime` wouldn't we expect the first departure time to be 08:00, the second 09:00, but the third one 09:15? As far I understand, this is how things are interpreted in the QSim and in the TimeMutator. However, `PlanRouter` uses a departure time of `10:00` here.

The reason is that it calls `PlanRouter.calcEndOfActivity` which has a "shortcut" in the beginning, which *always* returns the activity end time *if* it exists (which *always* needs to be the case if `minOfDurationAndEndTime` is used).

Or did I interpret wrongly what should happen here? I added a branch with a unit test that shows the current behaviour (`PlanRouterTest`): 
https://github.com/matsim-org/matsim-libs/tree/plan-router-departure-times

**Comment by sebhoerl** [comment]
There is a related issue (added in the same branch and class as `testSummingUpTravelTimesAndActivityEndTimes`).

Assume the plan
```
Activity (end time 1000)
Leg (routed travel time 1000)
Activity (end time 1200)
Leg (routed travel time 1000)
Activity (end time 1300)
Leg
Activity
```

Since the `PlanRouter` *routes* the trips, we know that the agent arrives at the second activity at 2000. Which would mean the activity has a duration of zero in the QSim, so we already know that the departure for the second trip would be at 2000. Again, for the third trip we know that the departure would be at 3000.

What the `PlanRouter` does, however, is to reset the departure times for the trips to 1200 and 1300, respectively. While routing we therefore assume the wrong departure time. This is unfortunate as the route is based on the time-of-day-dependent network travel times.

There is a trade-off: If we use the actual departure time, the written plan will be inconsistent, because the leg departure time will not fit to the activity end time. However, if we use the activity end time as the departure time, the route is not consistent.

Is this something that has already been discussed?

**Comment by sebhoerl** [comment]
I just added a couple of classes to the DMC extension, which perform all the time calculation. Rather than using static methods (which are a bit scattered over `PlanRouter`, `PopulationUtils`, ...) there is one interface `TimeInterpreter`, which then just offers methods such as `addLeg` and `addActivity`. The implementations of it are then the different interpretations. I could transfer this to the MATSim repository: https://github.com/matsim-eth/discrete-mode-choice/tree/develop/src/main/java/ch/ethz/matsim/discrete_mode_choice/replanning/time_interpreter

**Comment by sebhoerl** [comment]
Yet another issue: In the QSim an "undefined" `startTime` in the config translates to `00:00:00` (in `initSimTimer`), but theoretically the start time can be negative. In `PlanRouter.calcEndOfActivity` the start time when counting up activities is *always* set to zero. Probably quite a border case, but still, not consistent...

**Comment by michalmac** [comment]
Hmmm, while working on `OptionalTime`, I ran into similar issues, like:
`PopulationUtils.decideOnActivityEndTime()` is inconsistent with `ActivityDurationUtils.calculateDepartureTime()`. Not sure how much of the inconsistencies comes from a different context (replannning vs mobsim), and how much is just accidental.

**Comment by kainagel** [comment]
Thanks.  I would be very happy if all this could be cleaned up.  A centralized `TimeInterpreter` that everybody finds and uses would certainly be good; please go ahead and move it into the code.  It used to be the case that all code pieces implemented their own interpretation; I started centralizing them as static methods; but clearly that could be more systematic.

Having said this, I want to re-iterate that the design is that the mobsim is the referee of everything.  So the interpretation of the mobsim is what counts.  The innovative strategies are expected to spit out solution alternatives (= alternative plans).  The better they are matched to what happens in the mobsim, the more efficient they will probably be.  However, if they are too closely matched to what happens in the mobsim, and we change the mobsim (deliberately or inadvertedly), then they will suddenly fail.  This is why I personally like diversity in the strategies.  And this is also why I do not like when the scoring is circumvented, because then what suddenly counts is each strategy's own interpretation of the plan.

A last thing: `minOfDurationAndEndTime` is the "old" setting.  As far as I am concerned, we could deprecate it and phase it out.  It contains a rule-based version of within-day replanning, and we have found over the years that one should either do within-day replanning explicitly, or not at all.  Everything else leads to complications.  So a possible approach would be to either have activity `endTime` or activity `duration`, but not both.  Unfortunately, DTDs can't describe this.  So the `tryEndTimeThenDuration` is just an attempt to retrofit what we had.  There is also `VspPlansCleaner`, which attempts to remove attributes that are not used, in this case `duration` when there is already an `endTime`. (And yes, it is unfortunately not just called `duration` in the plans file.)

**Comment by sebhoerl** [comment]
Yes, makes all sense, would this be a viable way to go:

- [ ] Include `TimeInterpreter` and update the code pieces
- [ ] Add a (hidden / experimental?) config option to let the `PlanRouter` to optionally sum up time along the plan
- [ ] Open a new issue to maybe collect planned updated for a new version of the plans format / reader with `duration` as attribute and automatic detection if both are given

?

**Comment by kainagel** [comment]
Thanks.
Re (1) (`TimeInterpreter`): yes please.
Re (2) (switch): My intuition would be to migrate `PlanRouter` to the improved time interpretation, and have a switch for backwards compatibility.  Given that we do not know what comes up in the future, I would design this as an enum, something like `PlanRouterTripStartingTimeComputation`.  (Or add a separate `reRoute` config group, similar to the one that exists for `timeAllocationMutation`.)
Re (3) (dtd change/reader change): We somewhere have a list of planned changes for the next plans format update.  I keep not finding it :-).  -- I just put this particular item as comment into the dtd itself; hope that that is ok (currently in automerge).

**Comment by steffenaxer** [comment]
@sebhoerl What is the current status of this issue?
I trapped again in the very same problem, we discovered last year. Which causes inconsistant, non advancing departure times. Is it possible to make this component of MATSim replaceable, in terms of injection? @sebhoerl Do you see an easy way to retrofit embed the TimeInterpreter?
